/**
 * Branded exporters for Budget Builder and Expense Tracker — CSV, Excel (.xlsx)
 * and PDF. Heavy libraries (xlsx, jspdf) are dynamically imported so they never
 * enter the main bundle; they load only when the user actually exports.
 *
 * Exports are built from the caller's complete data set, never from what the
 * screen happens to be rendering: pagination, virtualisation and "recent N"
 * previews are display concerns and must never reach a report.
 *
 * Every export carries FinatriX branding, the generation date (local time), the
 * active currency, totals and a summary; PDFs add the full report layout from
 * pdfReport.ts (masthead, stat cards, charts, ruled tables, page numbers).
 */
import { cfmt } from './format';
import { budgetTone, TONE_EXPORT_LABEL } from './budgetStatus';
import {
  MARGIN, TABLE_STYLES, TONE_RGB, GOLD, INK, contentW, ensureSpace,
  drawDonut, drawGroupedBars, drawHeader, drawStatCards,
  loadLogo, money, pct, sectionTitle, stampFooters,
  type Doc, type StatCard,
} from './pdfReport';

const FOOT_NOTE = 'Generated by FinatriX  ·  Educational tool, not financial advice';

function stamp(): string {
  return new Date().toLocaleString(undefined, {
    day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit',
  });
}

/**
 * Hand a generated file to the browser.
 *
 * Two details are load-bearing, and both were wrong:
 *
 *  - The anchor is put IN the document before it is clicked. A synthetic click
 *    on a detached anchor is ignored outright by some engines, which is a silent
 *    failure — no download, no error, nothing in the console.
 *  - The object URL is revoked on a later task, not on the next line. Revoking
 *    synchronously after `click()` races the browser's own read of the blob:
 *    Chrome had usually finished, but Firefox and WebKit frequently had not, and
 *    the download aborted. The user's only signal was an Export button that
 *    appeared to do nothing — on the report that took the longest to generate.
 *
 * The delay is generous because the cost of being wrong is asymmetric: an object
 * URL held a moment too long costs a few bytes, one released too early costs the
 * export.
 */
export function downloadBlob(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.rel = 'noopener';
  a.style.display = 'none';
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    a.remove();
    URL.revokeObjectURL(url);
  }, 10_000);
}

/** Y position after the last autoTable (added on the doc by the plugin at runtime). */
function lastY(doc: unknown, fallback: number): number {
  const y = (doc as { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY;
  return typeof y === 'number' ? y : fallback;
}

function csvCell(v: string | number): string {
  return `"${String(v).replace(/"/g, '""')}"`;
}
function toCsv(rows: (string | number)[][]): string {
  return rows.map((r) => r.map(csvCell).join(',')).join('\n');
}
/**
 * CSV as a UTF-8 blob with a BOM. Without the BOM Excel decodes the file as the
 * system codepage and every non-ASCII currency symbol (₹, €, ¥) arrives mangled.
 */
function csvBlob(rows: (string | number)[][]): Blob {
  return new Blob(['﻿' + toCsv(rows)], { type: 'text/csv;charset=utf-8' });
}

function slug(s: string): string {
  return s.replace(/\s+/g, '-').toLowerCase();
}

/** Character-count truncation for card sub-lines (font-state independent). */
function clip(s: string, max: number): string {
  return s.length <= max ? s : s.slice(0, max - 1) + '…';
}

/* ────────────────────────── Budget ────────────────────────── */
export interface BudgetExportRow { group: string; label: string; amount: number }
export interface BudgetIncomeRow { label: string; amount: number }
export interface BudgetExport {
  monthLabel: string;
  currency: string;
  income: number;
  needs: { pct: number; limit: number; actual: number };
  wants: { pct: number; limit: number; actual: number };
  save: { pct: number; limit: number; actual: number };
  rows: BudgetExportRow[];
  spent: number;
  free: number;
  pos: boolean;
  savePct: number;
  allocatedPct: number;
  tips: string[];
  /** Per-source income breakdown (optional — absent for legacy single-field income). */
  incomeRows?: BudgetIncomeRow[];
}

function budgetMatrix(b: BudgetExport): (string | number)[][] {
  const fmtMoney = (n: number) => cfmt(n, b.currency);
  const head: (string | number)[][] = [
    ['FinatriX — Budget Builder'],
    [`Month: ${b.monthLabel}`, `Currency: ${b.currency}`, `Generated: ${stamp()}`],
    [],
    ['Summary', 'Percent', 'Limit', 'Actual'],
    ['Income', '', '', fmtMoney(b.income)],
    [`Needs`, `${b.needs.pct}%`, fmtMoney(b.needs.limit), fmtMoney(b.needs.actual)],
    [`Wants`, `${b.wants.pct}%`, fmtMoney(b.wants.limit), fmtMoney(b.wants.actual)],
    [`Savings`, `${b.save.pct}%`, fmtMoney(b.save.limit), fmtMoney(b.save.actual)],
    ['Allocated', `${b.allocatedPct}%`, '', fmtMoney(b.spent)],
    [b.pos ? 'Unallocated' : 'Over budget by', '', '', fmtMoney(Math.abs(b.free))],
    ['Actual savings rate', `${b.savePct}%`, '', ''],
  ];
  if (b.incomeRows?.length) {
    head.push([], ['Income source', 'Amount'], ...b.incomeRows.map((r) => [r.label, r.amount]));
  }
  head.push([], ['Group', 'Category', 'Amount'], ...b.rows.map((r) => [r.group, r.label, r.amount]));
  if (b.tips.length) {
    head.push([], ['Recommendations'], ...b.tips.map((t) => [t]));
  }
  return head;
}

export function exportBudgetCsv(b: BudgetExport) {
  downloadBlob(`finatrix-budget-${slug(b.monthLabel)}.csv`, csvBlob(budgetMatrix(b)));
}

export async function exportBudgetXlsx(b: BudgetExport) {
  const XLSX = await import('xlsx');
  const fmtMoney = (n: number) => cfmt(n, b.currency);
  const wb = XLSX.utils.book_new();
  const summary = XLSX.utils.aoa_to_sheet([
    ['FinatriX — Budget Builder'],
    [`Month: ${b.monthLabel}`],
    [`Currency: ${b.currency}`],
    [`Generated: ${stamp()}`],
    [],
    ['Item', 'Percent', 'Limit', 'Actual'],
    ['Income', '', '', fmtMoney(b.income)],
    ['Needs', `${b.needs.pct}%`, fmtMoney(b.needs.limit), fmtMoney(b.needs.actual)],
    ['Wants', `${b.wants.pct}%`, fmtMoney(b.wants.limit), fmtMoney(b.wants.actual)],
    ['Savings', `${b.save.pct}%`, fmtMoney(b.save.limit), fmtMoney(b.save.actual)],
    ['Allocated', `${b.allocatedPct}%`, '', fmtMoney(b.spent)],
    [b.pos ? 'Unallocated' : 'Over budget by', '', '', fmtMoney(Math.abs(b.free))],
    ['Actual savings rate', `${b.savePct}%`, '', ''],
  ]);
  summary['!cols'] = [{ wch: 22 }, { wch: 10 }, { wch: 16 }, { wch: 16 }];
  XLSX.utils.book_append_sheet(wb, summary, 'Summary');

  if (b.incomeRows?.length) {
    const inc = XLSX.utils.aoa_to_sheet([['Income source', 'Amount'], ...b.incomeRows.map((r) => [r.label, r.amount])]);
    inc['!cols'] = [{ wch: 24 }, { wch: 14 }];
    XLSX.utils.book_append_sheet(wb, inc, 'Income');
  }

  const cats = XLSX.utils.aoa_to_sheet([['Group', 'Category', 'Amount'], ...b.rows.map((r) => [r.group, r.label, r.amount])]);
  cats['!cols'] = [{ wch: 12 }, { wch: 24 }, { wch: 14 }];
  XLSX.utils.book_append_sheet(wb, cats, 'Categories');

  if (b.tips.length) {
    const tips = XLSX.utils.aoa_to_sheet([['Recommendations'], ...b.tips.map((t) => [t])]);
    tips['!cols'] = [{ wch: 90 }];
    XLSX.utils.book_append_sheet(wb, tips, 'Recommendations');
  }
  const out = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  downloadBlob(`finatrix-budget-${slug(b.monthLabel)}.xlsx`,
    new Blob([out], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }));
}

export async function exportBudgetPdf(b: BudgetExport) {
  const [{ jsPDF }, autoTableMod, logo] = await Promise.all([
    import('jspdf'), import('jspdf-autotable'), loadLogo(),
  ]);
  const autoTable = autoTableMod.default;
  const doc = new jsPDF({ unit: 'pt', format: 'a4' }) as Doc;
  const m = (n: number) => money(n, b.currency);

  let y = drawHeader(doc, { title: 'Budget Report', period: b.monthLabel, currency: b.currency, logo });

  y = drawStatCards(doc, y, [
    { label: 'Monthly income', value: m(b.income), accent: TONE_RGB.complete },
    { label: 'Allocated', value: m(b.spent), note: `${b.allocatedPct}% of income`, accent: GOLD },
    {
      label: b.pos ? 'Unallocated' : 'Over budget by',
      value: m(Math.abs(b.free)),
      note: b.pos ? 'Still to assign' : 'Trim to rebalance',
      accent: b.pos ? TONE_RGB.safe : TONE_RGB.over,
    },
    { label: 'Needs', value: m(b.needs.actual), note: `of ${m(b.needs.limit)} · ${b.needs.pct}%`, accent: TONE_RGB.complete },
    { label: 'Wants', value: m(b.wants.actual), note: `of ${m(b.wants.limit)} · ${b.wants.pct}%`, accent: TONE_RGB.warn },
    { label: 'Savings', value: m(b.save.actual), note: `${b.savePct}% actual savings rate`, accent: TONE_RGB.safe },
  ]);

  /* 50/30/20 split bar */
  y = sectionTitle(doc, y, 'Your split', `Target ${b.needs.pct} / ${b.wants.pct} / ${b.save.pct}`);
  const barW = contentW(doc);
  const total = b.needs.limit + b.wants.limit + b.save.limit || 1;
  let x = MARGIN;
  ([
    [b.needs.limit, TONE_RGB.complete],
    [b.wants.limit, TONE_RGB.warn],
    [b.save.limit, TONE_RGB.safe],
  ] as const).forEach(([val, rgb]) => {
    const w = (val / total) * barW;
    doc.setFillColor(...rgb);
    doc.rect(x, y, w, 14, 'F');
    x += w;
  });
  y += 28;

  y = sectionTitle(doc, y, 'Plan vs allocation');
  autoTable(doc, {
    ...TABLE_STYLES,
    startY: y,
    head: [['Item', 'Percent', 'Limit', 'Allocated']],
    body: [
      ['Income', '', '', m(b.income)],
      ['Needs', `${b.needs.pct}%`, m(b.needs.limit), m(b.needs.actual)],
      ['Wants', `${b.wants.pct}%`, m(b.wants.limit), m(b.wants.actual)],
      ['Savings', `${b.save.pct}%`, m(b.save.limit), m(b.save.actual)],
      ['Total allocated', `${b.allocatedPct}%`, '', m(b.spent)],
      [b.pos ? 'Unallocated' : 'Over budget by', '', '', m(Math.abs(b.free))],
    ],
    columnStyles: { 1: { halign: 'center' }, 2: { halign: 'right' }, 3: { halign: 'right' } },
  });
  y = lastY(doc, y) + 22;

  if (b.incomeRows?.length) {
    y = sectionTitle(doc, y, 'Income sources');
    autoTable(doc, {
      ...TABLE_STYLES,
      startY: y,
      head: [['Source', 'Amount', 'Share']],
      body: b.incomeRows.map((r) => [
        r.label, m(r.amount), b.income > 0 ? pct((r.amount / b.income) * 100) : '—',
      ]),
      columnStyles: { 1: { halign: 'right' }, 2: { halign: 'right' } },
    });
    y = lastY(doc, y) + 22;
  }

  y = sectionTitle(doc, y, 'Category allocations');
  autoTable(doc, {
    ...TABLE_STYLES,
    startY: y,
    head: [['Group', 'Category', 'Amount']],
    body: b.rows.map((r) => [r.group, r.label, m(r.amount)]),
    columnStyles: { 2: { halign: 'right' } },
  });
  y = lastY(doc, y) + 22;

  if (b.tips.length) {
    y = sectionTitle(doc, y, 'Recommendations');
    autoTable(doc, {
      ...TABLE_STYLES,
      startY: y,
      head: [['What we noticed']],
      body: b.tips.map((t) => [t]),
      headStyles: { ...TABLE_STYLES.headStyles, fillColor: GOLD },
    });
  }

  stampFooters(doc, FOOT_NOTE);
  doc.save(`finatrix-budget-${slug(b.monthLabel)}.pdf`);
}

/* ────────────────────────── Expense ────────────────────────── */

export interface ExpenseBreakdownRow {
  label: string;
  amount: number;
  pct: number;
  /**
   * False for savings, income and internal transfers. Those still appear in the
   * category breakdown (they are real money movements) but never rank as
   * "top spending".
   */
  spending?: boolean;
}

export interface ExpenseTxRow {
  date: string;
  category: string;
  amount: number;
  note: string;
  merchant?: string;
  paymentMethod?: string;
}

export interface ExpenseCategoryBudget {
  label: string;
  budget: number;
  spent: number;
}

export interface ExpenseExport {
  monthLabel: string;
  currency: string;
  totalSpent: number;
  dailyAvg: number;
  txCount: number;
  budget: number;
  breakdown: ExpenseBreakdownRow[];
  /** EVERY transaction in scope — never a page, a window or a "recent" slice. */
  transactions: ExpenseTxRow[];
  /* ── Optional richer context (absent callers still produce a valid report) ── */
  income?: number;
  monthlySavings?: number;
  netCashFlow?: number | null;
  budgetUsedPct?: number;
  daysInMonth?: number;
  daysRemaining?: number;
  /** Per-category budget vs spend — drives the chart and the comparison table. */
  categoryBudgets?: ExpenseCategoryBudget[];
}

function budgetRemainingOf(e: ExpenseExport): number {
  return e.budget - e.totalSpent;
}

/** Largest single transaction in the export (null when there are none). */
function largestExpense(e: ExpenseExport): ExpenseTxRow | null {
  return e.transactions.reduce<ExpenseTxRow | null>(
    (best, t) => (best == null || t.amount > best.amount ? t : best), null,
  );
}

/** Largest *spending* category — savings and transfers are excluded. */
function largestCategory(e: ExpenseExport): ExpenseBreakdownRow | null {
  return e.breakdown
    .filter((b) => b.spending !== false)
    .reduce<ExpenseBreakdownRow | null>((best, b) => (best == null || b.amount > best.amount ? b : best), null);
}

function txLabel(t: ExpenseTxRow): string {
  return t.merchant || t.note || t.category;
}

function expenseMatrix(e: ExpenseExport): (string | number)[][] {
  const fmtMoney = (n: number) => cfmt(n, e.currency);
  const rows: (string | number)[][] = [
    ['FinatriX — Expense Report'],
    [`Month: ${e.monthLabel}`, `Currency: ${e.currency}`, `Generated: ${stamp()}`],
    [],
    ['Summary'],
    ['Total spent', fmtMoney(e.totalSpent)],
    ['Daily average', fmtMoney(e.dailyAvg)],
    ['Transactions', e.txCount],
  ];
  if (e.income != null && e.income > 0) rows.push(['Total income', fmtMoney(e.income)]);
  if (e.monthlySavings != null) rows.push(['Savings', fmtMoney(e.monthlySavings)]);
  if (e.netCashFlow != null) rows.push(['Net cash flow', fmtMoney(e.netCashFlow)]);
  if (e.budget > 0) {
    rows.push(
      ['Budget', fmtMoney(e.budget)],
      ['Budget utilisation', `${Math.round(e.budgetUsedPct ?? (e.totalSpent / e.budget) * 100)}%`],
      ['Budget remaining', fmtMoney(budgetRemainingOf(e))],
    );
  }

  if (e.categoryBudgets?.length) {
    rows.push([], ['Category', 'Budget', 'Expense', 'Remaining', 'Status']);
    e.categoryBudgets.forEach((c) => rows.push([
      c.label, c.budget, c.spent, c.budget - c.spent, TONE_EXPORT_LABEL[budgetTone(c.budget, c.spent)],
    ]));
  }

  rows.push([], ['Category', 'Amount', 'Share']);
  e.breakdown.forEach((b) => rows.push([b.label, b.amount, `${b.pct}%`]));

  rows.push([], ['Date', 'Category', 'Merchant', 'Payment method', 'Amount', 'Note']);
  e.transactions.forEach((t) => rows.push([
    t.date, t.category, t.merchant ?? '', t.paymentMethod ?? '', t.amount, t.note,
  ]));
  return rows;
}

export function exportExpenseCsv(e: ExpenseExport) {
  downloadBlob(`finatrix-expenses-${slug(e.monthLabel)}.csv`, csvBlob(expenseMatrix(e)));
}

export async function exportExpenseXlsx(e: ExpenseExport) {
  const XLSX = await import('xlsx');
  const fmtMoney = (n: number) => cfmt(n, e.currency);
  const wb = XLSX.utils.book_new();
  const summaryRows: (string | number)[][] = [
    ['FinatriX — Expense Report'],
    [`Month: ${e.monthLabel}`], [`Currency: ${e.currency}`], [`Generated: ${stamp()}`],
    [],
    ['Total spent', fmtMoney(e.totalSpent)],
    ['Daily average', fmtMoney(e.dailyAvg)],
    ['Transactions', e.txCount],
  ];
  if (e.income != null && e.income > 0) summaryRows.push(['Total income', fmtMoney(e.income)]);
  if (e.monthlySavings != null) summaryRows.push(['Savings', fmtMoney(e.monthlySavings)]);
  if (e.netCashFlow != null) summaryRows.push(['Net cash flow', fmtMoney(e.netCashFlow)]);
  if (e.budget > 0) {
    summaryRows.push(
      ['Budget', fmtMoney(e.budget)],
      ['Budget utilisation', `${Math.round(e.budgetUsedPct ?? (e.totalSpent / e.budget) * 100)}%`],
      ['Budget remaining', fmtMoney(budgetRemainingOf(e))],
    );
  }
  summaryRows.push([], ['Category', 'Amount', 'Share'], ...e.breakdown.map((b) => [b.label, b.amount, `${b.pct}%`]));
  const summary = XLSX.utils.aoa_to_sheet(summaryRows);
  summary['!cols'] = [{ wch: 22 }, { wch: 16 }, { wch: 10 }];
  XLSX.utils.book_append_sheet(wb, summary, 'Summary');

  if (e.categoryBudgets?.length) {
    const bvs = XLSX.utils.aoa_to_sheet([
      ['Category', 'Budget', 'Expense', 'Remaining', 'Status'],
      ...e.categoryBudgets.map((c) => [
        c.label, c.budget, c.spent, c.budget - c.spent, TONE_EXPORT_LABEL[budgetTone(c.budget, c.spent)],
      ]),
    ]);
    bvs['!cols'] = [{ wch: 24 }, { wch: 14 }, { wch: 14 }, { wch: 14 }, { wch: 14 }];
    XLSX.utils.book_append_sheet(wb, bvs, 'Budget vs Expense');
  }

  const tx = XLSX.utils.aoa_to_sheet([
    ['Date', 'Category', 'Merchant', 'Payment method', 'Amount', 'Note'],
    ...e.transactions.map((t) => [t.date, t.category, t.merchant ?? '', t.paymentMethod ?? '', t.amount, t.note]),
  ]);
  tx['!cols'] = [{ wch: 12 }, { wch: 18 }, { wch: 22 }, { wch: 16 }, { wch: 12 }, { wch: 40 }];
  XLSX.utils.book_append_sheet(wb, tx, 'Transactions');

  const out = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  downloadBlob(`finatrix-expenses-${slug(e.monthLabel)}.xlsx`,
    new Blob([out], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }));
}

/**
 * The full expense report.
 *
 * Page 1 leads with the summary a reader needs first (income, expenses,
 * savings, budget utilisation, remaining, net cash flow), then budget vs
 * expense as a chart and as a table, then the spending highlights and the
 * category mix. Every transaction follows in a ruled table — all of them,
 * however many there are; the table paginates, the data is never truncated.
 */
export async function exportExpensePdf(e: ExpenseExport) {
  const [{ jsPDF }, autoTableMod, logo] = await Promise.all([
    import('jspdf'), import('jspdf-autotable'), loadLogo(),
  ]);
  const autoTable = autoTableMod.default;
  const doc = new jsPDF({ unit: 'pt', format: 'a4' }) as Doc;
  const m = (n: number) => money(n, e.currency);

  let y = drawHeader(doc, {
    title: 'Expense Report', period: e.monthLabel, currency: e.currency, logo,
  });

  /* ── Summary cards ── */
  const used = e.budgetUsedPct ?? (e.budget > 0 ? (e.totalSpent / e.budget) * 100 : 0);
  const remaining = budgetRemainingOf(e);
  const cards: StatCard[] = [
    {
      label: 'Total income',
      value: e.income != null && e.income > 0 ? m(e.income) : '—',
      note: e.income != null && e.income > 0 ? 'From Budget Builder' : 'Set income in Budget Builder',
      accent: TONE_RGB.complete,
    },
    { label: 'Total expenses', value: m(e.totalSpent), note: `${e.txCount} transactions`, accent: TONE_RGB.warn },
    {
      label: 'Savings',
      value: e.monthlySavings != null ? m(e.monthlySavings) : '—',
      note: e.income != null && e.income > 0 && e.monthlySavings != null
        ? `${pct((e.monthlySavings / e.income) * 100)} of income`
        : 'Savings-category spend',
      accent: TONE_RGB.safe,
    },
    {
      label: 'Budget utilisation',
      value: e.budget > 0 ? pct(used) : '—',
      note: e.budget > 0 ? `of ${m(e.budget)} budget` : 'No budget set',
      accent: TONE_RGB[budgetTone(e.budget, e.totalSpent)],
    },
    {
      label: e.budget > 0 && remaining < 0 ? 'Budget overrun' : 'Budget remaining',
      value: e.budget > 0 ? m(Math.abs(remaining)) : '—',
      note: e.daysRemaining != null && e.daysRemaining > 0 ? `${e.daysRemaining} days left in month` : 'Month complete',
      accent: remaining < 0 ? TONE_RGB.over : TONE_RGB.safe,
    },
    {
      label: 'Net cash flow',
      value: e.netCashFlow != null ? m(e.netCashFlow) : '—',
      note: e.netCashFlow != null ? (e.netCashFlow >= 0 ? 'Income exceeds spending' : 'Spending exceeds income') : 'Needs an income figure',
      accent: (e.netCashFlow ?? 0) >= 0 ? TONE_RGB.safe : TONE_RGB.over,
    },
  ];
  y = drawStatCards(doc, y, cards);

  /* ── Budget vs expense ── */
  const budgeted = (e.categoryBudgets ?? []).filter((c) => c.budget > 0 || c.spent > 0);
  if (budgeted.length > 0) {
    const chartRows = [...budgeted]
      .sort((a, b) => Math.max(b.budget, b.spent) - Math.max(a.budget, a.spent))
      .slice(0, 10);
    y = sectionTitle(doc, y, 'Budget vs expense', `Top ${chartRows.length} categories by size`);
    y = drawGroupedBars(doc, y, chartRows.map((c) => ({ label: c.label, budget: c.budget, spent: c.spent })), e.currency);

    y = sectionTitle(doc, y, 'Category detail');
    autoTable(doc, {
      ...TABLE_STYLES,
      startY: y,
      head: [['Category', 'Budget', 'Expense', 'Remaining', 'Status']],
      body: [...budgeted]
        .sort((a, b) => b.spent - a.spent)
        .map((c) => [
          c.label, m(c.budget), m(c.spent), m(c.budget - c.spent),
          TONE_EXPORT_LABEL[budgetTone(c.budget, c.spent)],
        ]),
      columnStyles: {
        1: { halign: 'right' }, 2: { halign: 'right' }, 3: { halign: 'right' },
        4: { halign: 'center', fontStyle: 'bold' },
      },
      // Colour the status column to match the app's own tone scale, so the
      // printed table carries the same signal as the screen.
      didParseCell: (raw: unknown) => {
        const data = raw as {
          section: string; column: { index: number };
          cell: { text: string[]; styles: { textColor: unknown } };
        };
        if (data.section !== 'body' || data.column.index !== 4) return;
        const label = data.cell.text?.[0];
        const tone = (Object.keys(TONE_EXPORT_LABEL) as Array<keyof typeof TONE_EXPORT_LABEL>)
          .find((k) => TONE_EXPORT_LABEL[k] === label);
        if (tone) data.cell.styles.textColor = TONE_RGB[tone];
      },
    });
    y = lastY(doc, y) + 22;
  }

  /* ── Spending highlights ── */
  const big = largestExpense(e);
  const topCat = largestCategory(e);
  y = sectionTitle(doc, y, 'Top spending');
  y = drawStatCards(doc, y, [
    {
      label: 'Largest expense',
      value: big ? m(big.amount) : '—',
      note: big ? clip(`${txLabel(big)} · ${big.date}`, 34) : 'No transactions',
      accent: TONE_RGB.over,
    },
    { label: 'Average daily spending', value: m(e.dailyAvg), note: e.daysInMonth ? `Across ${e.daysInMonth} days` : 'This period', accent: GOLD },
    {
      label: 'Largest category',
      value: topCat ? m(topCat.amount) : '—',
      note: topCat ? clip(`${topCat.label} · ${pct(topCat.pct)} of spend`, 34) : 'No spending yet',
      accent: TONE_RGB.warn,
    },
  ]);

  /* ── Category breakdown ── */
  if (e.breakdown.length > 0) {
    y = sectionTitle(doc, y, 'Category breakdown', 'Share of everything logged this period');
    y = drawDonut(doc, y, e.breakdown.map((b) => ({ label: b.label, amount: b.amount })), e.currency);
  }

  /* ── All transactions ── */
  // Continue on this page when there is room for the heading and a few rows;
  // an unconditional page break here left half-empty pages in the middle of the
  // report. autoTable paginates the rest on its own.
  const ty = sectionTitle(
    doc, ensureSpace(doc, y, 150),
    'All transactions', `${e.transactions.length} of ${e.txCount} for ${e.monthLabel}`,
  );
  autoTable(doc, {
    ...TABLE_STYLES,
    startY: ty,
    head: [['Date', 'Category', 'Merchant / note', 'Payment', 'Amount']],
    body: e.transactions.map((t) => [
      t.date,
      t.category,
      [t.merchant, t.note].filter(Boolean).join(' — '),
      t.paymentMethod ?? '',
      m(t.amount),
    ]),
    columnStyles: {
      0: { cellWidth: 62 }, 3: { cellWidth: 66 },
      4: { halign: 'right', cellWidth: 78, fontStyle: 'bold', textColor: INK },
    },
    foot: [['', '', '', 'Total', m(e.totalSpent)]],
    footStyles: { fillColor: [240, 238, 232], textColor: INK, fontStyle: 'bold', fontSize: 8.5, halign: 'right' },
  });

  stampFooters(doc, FOOT_NOTE);
  doc.save(`finatrix-expenses-${slug(e.monthLabel)}.pdf`);
}
