/**
 * The master source registry — 105 dated, checkable references.
 *
 * WHY IDS AND NOT URLS
 * --------------------
 * Before this file, provenance lived as prose inside each market pack:
 * "ONS Household Total Wealth statistics" in one place, "Published best-buy
 * rates" in another, "Income Tax Act provisions current for AY 2026-27" in a
 * third. Three problems followed. A reader could not click any of them. The
 * same authority was described differently depending on which tool you were
 * looking at. And nothing carried a date, so a source could quietly stop
 * describing current law without anything in the product noticing.
 *
 * An id fixes all three. `UK-FSCS-001` resolves to one record with a URL, an
 * effective date, a verification date and a review date, and every tool that
 * cites the FSCS cites the same record. When the URL changes the record's URL
 * changes and the id does not, so saved results keep pointing at the right
 * thing.
 *
 * ON `lastVerified`
 * -----------------
 * Every date here is 2026-09-12 because that is when the independent research
 * pack these records came from was compiled. FinatriX did not re-open 105
 * government pages; it imported a dated extraction, and the honest thing is to
 * carry that date rather than stamp today's. `verificationScope` says what was
 * actually checked — the extracted claim, never the whole page.
 *
 * ON TIERS
 * --------
 * A tier describes what KIND of body published something, not how much to trust
 * it. Legislation is tier 1 and has nothing to say about consumer price indices;
 * a national statistics office is tier 4 and is the only acceptable authority on
 * its own household survey. `preferSourceFor` in `resolve.ts` ranks by topic
 * competence first and tier second, for exactly that reason.
 *
 * GENERATED-SHAPED, MAINTAINED BY HAND. Records are ordered by market then
 * topic. Adding one means adding a record here and nowhere else.
 */

import type { ReferenceSource } from './types';

export const SOURCES: readonly ReferenceSource[] = [
  {
    id: 'IND-DICGC-001',
    market: 'IN',
    topic: 'deposit',
    authority: 'DICGC',
    title: 'FAQ',
    url: 'https://www.dicgc.org.in/FAQs',
    effectiveDate: '2020-02-04',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Ownership treatment; commencement corroborated by IND-DICGC-002.',
  },
  {
    id: 'AUS-APRA-001',
    market: 'AU',
    topic: 'deposit',
    authority: 'APRA',
    title: 'Financial Claims Scheme: Banks, building societies and credit unions',
    url: 'https://www.apra.gov.au/financial-claims-scheme-banks-building-societies-and-credit-unions',
    effectiveDate: '2012-02-01',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 2,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'AUS-APRA-002',
    market: 'AU',
    topic: 'deposit',
    authority: 'APRA',
    title: 'Frequently asked questions about banking and the Financial Claims Scheme',
    url: 'https://www.apra.gov.au/frequently-asked-questions-about-banking-and-financial-claims-scheme',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 2,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'AUS-APRA-003',
    market: 'AU',
    topic: 'deposit',
    authority: 'APRA',
    title: 'Mutuals in unsettled times',
    url: 'https://www.apra.gov.au/news-and-publications/mutuals-unsettled-times',
    effectiveDate: '2012-02-01',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 2,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Historical commencement corroboration. Later paragraph has 2102 typo; opening explicitly says 2012.',
  },
  {
    id: 'US-FDIC-001',
    market: 'US',
    topic: 'deposit',
    authority: 'FDIC',
    title: 'Your Insured Deposits',
    url: 'https://www.fdic.gov/resources/deposit-insurance/brochures/insured-deposits',
    effectiveDate: '2010-07-21',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'US-FDIC-002',
    market: 'US',
    topic: 'deposit',
    authority: 'FDIC',
    title: 'Basic FDIC Insurance Coverage Permanently Increased to $250,000 Per Depositor',
    url: 'https://archive.fdic.gov/view/fdic/4000/fdic_4000_DS1.pdf',
    effectiveDate: '2010-07-21',
    publicationDate: '2010-07-21',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'UK-FSCS-001',
    market: 'GB',
    topic: 'deposit',
    authority: 'FSCS',
    title: 'Deposit protection limit',
    url: 'https://www.fscs.org.uk/what-we-cover/banks-building-societies-credit-unions/deposit-limit/',
    effectiveDate: '2025-12-01',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'UK-FSCS-002',
    market: 'GB',
    topic: 'deposit',
    authority: 'FSCS',
    title: 'Deposit protection Q&As - banks & building societies',
    url: 'https://www.fscs.org.uk/industry-resources/deposit-protection-banks/',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'SG-SDIC-001',
    market: 'SG',
    topic: 'deposit',
    authority: 'SDIC',
    title: 'Deposit Insurance Scheme – FAQs',
    url: 'https://sdic.org.sg/di_faq/',
    effectiveDate: '2024-04-01',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'SG-SDIC-002',
    market: 'SG',
    topic: 'deposit',
    authority: 'SDIC',
    title: 'Deposit insurance limit goes up to $100,000 from today',
    url: 'https://sdic.org.sg/api/207/Deposit%20insurance%20limit%20goes%20up%20to%20100000%20from%20today%20SDIC%20launches%20public%20education%20campaign.pdf',
    effectiveDate: '2024-04-01',
    publicationDate: '2024-04-01',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'CN-MOJ-001',
    market: 'CN',
    topic: 'deposit',
    authority: 'Ministry of Justice / State Council',
    title: '存款保险条例 — Deposit Insurance Regulations',
    url: 'https://xzfg.moj.gov.cn/law/download?LawID=419&type=pdf',
    effectiveDate: '2015-05-01',
    publicationDate: '2015-02-17',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'zh-Hans',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Articles 2, 4, 5. Binding text distinguishes foreign bank branches, not all foreign-owned banks.',
  },
  {
    id: 'CN-SPP-001',
    market: 'CN',
    topic: 'deposit',
    authority: 'Supreme People’s Procuratorate / State Council',
    title: '存款保险条例',
    url: 'https://www.spp.gov.cn/flfg/201504/t20150401_94352.shtml',
    effectiveDate: '2015-05-01',
    publicationDate: '2015-04-01',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'zh-Hans',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'UAE-CBUAE-001',
    market: 'AE',
    topic: 'deposit',
    authority: 'CBUAE',
    title: 'Article (122): Deposits Guarantee Scheme',
    url: 'https://rulebook.centralbank.ae/en/rulebook/article-122-deposits-guarantee-scheme',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 2,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Enabling provision only; not evidence of an operational retail guarantee cap. Supersession must be checked.',
  },
  {
    id: 'UAE-CBUAE-002',
    market: 'AE',
    topic: 'deposit',
    authority: 'CBUAE',
    title: 'Central Bank law / entire section',
    url: 'https://rulebook.centralbank.ae/en/entiresection/42',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 2,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Current-law discovery route; no retail cap verified. Do not confuse insurer guarantee deposits with retail bank insurance.',
  },
  {
    id: 'AUS-ATO-001',
    market: 'AU',
    topic: 'tax',
    authority: 'Australian Parliament / ATO',
    title: 'Treasury Laws Amendment (More Cost of Living Relief) Act 2025',
    url: 'https://www.ato.gov.au/law/view/pdf/acts/20250028.pdf',
    effectiveDate: '2026-07-01',
    publicationDate: '2025-03-31',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'TAX_YEAR_AND_BUDGET',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: '2026–27 marginal rate schedule; 2027–28 lower-band rate is a separate future version.',
  },
  {
    id: 'AUS-ATO-002',
    market: 'AU',
    topic: 'retirement',
    authority: 'ATO',
    title: 'Super guarantee',
    url: 'https://www.ato.gov.au/tax-rates-and-codes/key-superannuation-rates-and-thresholds/super-guarantee',
    effectiveDate: '2026-07-01',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Extracted 2026–27 general and Norfolk Island rate schedule; stale quarterly payment wording not adopted.',
  },
  {
    id: 'AUS-ATO-003',
    market: 'AU',
    topic: 'retirement',
    authority: 'ATO',
    title: 'Key super rates and thresholds',
    url: 'https://www.ato.gov.au/tax-rates-and-codes/key-superannuation-rates-and-thresholds',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Accessible extract contains older periods; 2026–27 caps not treated as verified from this page.',
  },
  {
    id: 'AUS-CSC-001',
    market: 'AU',
    topic: 'retirement',
    authority: 'Commonwealth Superannuation Corporation',
    title: 'Federal Budget 2026/27',
    url: 'https://www.csc.gov.au/advisers/news/2026-05-federal-budget-2026-27',
    effectiveDate: '2026-07-01',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Corroboration of updated caps; ATO current-period confirmation remains release gate.',
  },
  {
    id: 'AUS-ASIC-001',
    market: 'AU',
    topic: 'retirement',
    authority: 'ASIC Moneysmart',
    title: 'Super and pension age calculator',
    url: 'https://moneysmart.gov.au/plan-for-your-retirement/super-and-pension-age-calculator',
    effectiveDate: null,
    publicationDate: '2026-03-22',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 2,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'AUS-SA-001',
    market: 'AU',
    topic: 'retirement',
    authority: 'Services Australia',
    title: 'Who can get Age Pension',
    url: 'https://www.servicesaustralia.gov.au/who-can-get-age-pension?context=22526',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Age alone is insufficient: residence, income and assets apply.',
  },
  {
    id: 'US-IRS-001',
    market: 'US',
    topic: 'tax',
    authority: 'IRS',
    title: 'IRS releases tax inflation adjustments for tax year 2026, including amendments from the One, Big, Beautiful Bill',
    url: 'https://www.irs.gov/newsroom/irs-releases-tax-inflation-adjustments-for-tax-year-2026-including-amendments-from-the-one-big-beautiful-bill',
    effectiveDate: '2026-01-01',
    publicationDate: '2025-10-09',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'TAX_YEAR_AND_BUDGET',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'US-IRS-002',
    market: 'US',
    topic: 'tax',
    authority: 'IRS',
    title: 'Internal Revenue Bulletin 2025-45 / Revenue Procedure 2025-32',
    url: 'https://www.irs.gov/irb/2025-45_IRB',
    effectiveDate: '2026-01-01',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'TAX_YEAR_AND_BUDGET',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'US-IRS-003',
    market: 'US',
    topic: 'retirement',
    authority: 'IRS',
    title: '401(k) limit increases to $24,500 for 2026, IRA limit increases to $7,500',
    url: 'https://www.irs.gov/newsroom/401k-limit-increases-to-24500-for-2026-ira-limit-increases-to-7500',
    effectiveDate: '2026-01-01',
    publicationDate: '2025-11-13',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'US-SSA-001',
    market: 'US',
    topic: 'retirement',
    authority: 'SSA',
    title: '2026 Cost-of-Living Adjustment (COLA) Fact Sheet',
    url: 'https://www.ssa.gov/cola/factsheets/2026.html',
    effectiveDate: '2026-01-01',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'US-SSA-002',
    market: 'US',
    topic: 'retirement',
    authority: 'SSA',
    title: 'Retirement Age Calculator',
    url: 'https://www.ssa.gov/benefits/retirement/planner/ageincrease.html',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'UK-HMRC-001',
    market: 'GB',
    topic: 'tax',
    authority: 'HMRC',
    title: 'Income Tax rates and allowances for current and previous tax years',
    url: 'https://www.gov.uk/government/publications/rates-and-allowances-income-tax/income-tax-rates-and-allowances-current-and-past',
    effectiveDate: '2026-04-06',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'TAX_YEAR_AND_BUDGET',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'UK-HMRC-002',
    market: 'GB',
    topic: 'tax',
    authority: 'HMRC',
    title: 'Rates and thresholds for employers 2026 to 2027',
    url: 'https://www.gov.uk/guidance/rates-and-thresholds-for-employers-2026-to-2027',
    effectiveDate: '2026-04-06',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'TAX_YEAR_AND_BUDGET',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'UK-HMRC-003',
    market: 'GB',
    topic: 'tax',
    authority: 'HMRC',
    title: 'Income Tax in Scotland: Current rates',
    url: 'https://www.gov.uk/scottish-income-tax',
    effectiveDate: '2026-04-06',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'en',
    scope: 'REGION_SPECIFIC',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Scottish earned income; savings and dividends follow UK treatment.',
  },
  {
    id: 'UK-HMRC-004',
    market: 'GB',
    topic: 'tax',
    authority: 'HMRC',
    title: 'Capital Gains Tax rates',
    url: 'https://www.gov.uk/capital-gains-tax/rates',
    effectiveDate: '2026-04-06',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'UK-DWP-001',
    market: 'GB',
    topic: 'retirement',
    authority: 'DWP',
    title: 'Workplace pensions: What you, your employer and the government pay',
    url: 'https://www.gov.uk/workplace-pensions/what-you-your-employer-and-the-government-pay',
    effectiveDate: '2019-04-06',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'UK-DWP-002',
    market: 'GB',
    topic: 'retirement',
    authority: 'DWP',
    title: 'State Pension age timetable',
    url: 'https://www.gov.uk/government/publications/state-pension-age-timetable/state-pension-age-timetable',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'IND-ITD-001',
    market: 'IN',
    topic: 'tax',
    authority: 'Income Tax Department',
    title: 'Salaried Individuals for AY 2026-27',
    url: 'https://www.incometax.gov.in/iec/foportal/help/individual/return-applicable-1',
    effectiveDate: '2025-04-01',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'FY2025–26 / AY2026–27 historical reference; do not automatically apply to FY2026–27.',
  },
  {
    id: 'IND-ITD-002',
    market: 'IN',
    topic: 'tax',
    authority: 'Income Tax Department',
    title: 'FAQs Budget 2026 — Rate of income tax',
    url: 'https://www.incometaxindia.gov.in/documents/20117/15766092/FAQs-Budget-2026.pdf/ff3d0e10-88a0-b11f-3c27-b58375974227?download=true&t=1770036575267&version=1.0',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Explains transition to section 202; verify enacted current tax-year text before automation.',
  },
  {
    id: 'IND-EPFO-001',
    market: 'IN',
    topic: 'retirement',
    authority: 'EPFO',
    title: 'Employer Information Booklet',
    url: 'https://www.epfindia.gov.in/site_docs/PDFs/MiscPDFs/Employer_Information_Booklet.pdf',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'EPF/EPS wage-base, membership and international-worker exceptions.',
  },
  {
    id: 'IND-EPFO-002',
    market: 'IN',
    topic: 'retirement',
    authority: 'EPFO',
    title: 'Present Rates of Contribution',
    url: 'https://www.epfindia.gov.in/site_docs/PDFs/MiscPDFs/ContributionRate.pdf',
    effectiveDate: null,
    publicationDate: '2018-06-12',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Historical published rate sheet; verify applicability against current notifications before payroll modeling.',
  },
  {
    id: 'IND-PFRDA-001',
    market: 'IN',
    topic: 'retirement',
    authority: 'PFRDA',
    title: 'NPS All Citizen Model',
    url: 'https://pfrda.org.in/en/schemes/national-pension-system/nps-for-all-citizen-models',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Current non-government exit framework; not transferable to government subscribers.',
  },
  {
    id: 'IND-PFRDA-002',
    market: 'IN',
    topic: 'retirement',
    authority: 'PFRDA',
    title: 'FAQs - Exits & Withdrawals from NPS for All Citizen Model (Updated March 2026)',
    url: 'https://pfrda.org.in/documents/33652/676426/Exits%2Band%2BWithdrawals%2Bunder%2BNPS%2Bfor%2BAll%2BCitizen%2BModel.pdf',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'SG-IRAS-001',
    market: 'SG',
    topic: 'tax',
    authority: 'IRAS',
    title: 'Individual Income Tax rates',
    url: 'https://www.iras.gov.sg/taxes/individual-income-tax/basics-of-individual-income-tax/tax-residency-and-tax-rates/individual-income-tax-rates',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'From YA2024; YA is not the earning year. Annual rebates separate.',
  },
  {
    id: 'SG-IRAS-002',
    market: 'SG',
    topic: 'tax',
    authority: 'IRAS',
    title: 'Interest',
    url: 'https://www.iras.gov.sg/taxes/individual-income-tax/basics-of-individual-income-tax/what-is-taxable-what-is-not/interest',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'SG-IRAS-003',
    market: 'SG',
    topic: 'tax',
    authority: 'IRAS',
    title: 'Sale of property/shares/financial instruments gains',
    url: 'https://www.iras.gov.sg/taxes/individual-income-tax/basics-of-individual-income-tax/what-is-taxable-what-is-not/gains-from-sale-of-property-shares-and-financial-instruments',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'SG-CPF-001',
    market: 'SG',
    topic: 'retirement',
    authority: 'CPF Board',
    title: 'How much CPF contributions to pay',
    url: 'https://www.cpf.gov.sg/employer/employer-obligations/how-much-cpf-contributions-to-pay',
    effectiveDate: '2026-01-01',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'SG-CPF-002',
    market: 'SG',
    topic: 'retirement',
    authority: 'CPF Board',
    title: 'CPF Allocation Rates from 1 January 2026',
    url: 'https://www.cpf.gov.sg/content/dam/web/employer/employer-obligations/documents/CPFAllocationRatesfromJanuary2026.pdf',
    effectiveDate: '2026-01-01',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Rate-table source identified; allocation numbers not transcribed in this pack.',
  },
  {
    id: 'SG-CPF-003',
    market: 'SG',
    topic: 'retirement',
    authority: 'CPF Board',
    title: 'What is the closure of Special Account for members aged 55 and above about?',
    url: 'https://www.cpf.gov.sg/service/article/what-is-the-closure-of-special-account-for-members-aged-55-and-above-about',
    effectiveDate: '2025-01-19',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'SG-CPF-004',
    market: 'SG',
    topic: 'retirement',
    authority: 'CPF Board',
    title: 'Your complete guide to retirement planning in Singapore',
    url: 'https://www.cpf.gov.sg/member/infohub/educational-resources/your-complete-guide-to-retirement-planning-in-singapore',
    effectiveDate: '2026-01-01',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Retirement sums only extracted; payout examples are not defaults.',
  },
  {
    id: 'SG-CPF-005',
    market: 'SG',
    topic: 'retirement',
    authority: 'CPF Board',
    title: 'CPF contribution changes from 1 January 2027',
    url: 'https://www.cpf.gov.sg/employer/infohub/news/cpf-related-announcements/new-contribution-rates',
    effectiveDate: '2027-01-01',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Future effective; must not replace 2026 rules early.',
  },
  {
    id: 'UAE-FTA-001',
    market: 'AE',
    topic: 'tax',
    authority: 'Federal Tax Authority',
    title: 'Basic Tax Information Bulletin — Natural Persons',
    url: 'https://www.tax.gov.ae/Datafolder/Files/Pdf/2024/CT%20Bulletin/Basic%20Tax%20Information%20bulletin-%20Natural%20Person-English.pdf',
    effectiveDate: '2024-01-01',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Wages and qualifying personal investments excluded from natural-person business tax; other-country tax not addressed.',
  },
  {
    id: 'UAE-GOV-001',
    market: 'AE',
    topic: 'retirement',
    authority: 'UAE Government',
    title: 'End of service benefits for workers in the private sector',
    url: 'https://u.ae/en/information-and-services/jobs/employment-in-the-private-sector/end-of-service-benefits-for-employees-in-the-private-sector',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Federal private-sector frame; basic wage, contract and alternative scheme matter.',
  },
  {
    id: 'UAE-GPSSA-001',
    market: 'AE',
    topic: 'retirement',
    authority: 'GPSSA',
    title: 'GPSSA: An insured’s contribution payment may be extended to the 15th day of each month',
    url: 'https://www.gpssa.gov.ae/pages/en/media-center/news/gpssa-insureds-contribution-payment-may-be-extended-15th-day-each-month',
    effectiveDate: null,
    publicationDate: '2025-02-23',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Distinguishes 1999 and 2023 cohorts; no UAE-wide pension default.',
  },
  {
    id: 'CN-STA-001',
    market: 'CN',
    topic: 'tax',
    authority: 'State Taxation Administration',
    title: '中华人民共和国个人所得税法 — Individual Income Tax Law',
    url: 'https://www.chinatax.gov.cn/n810219/n810744/n3752930/n3752974/c3970366/content.html',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'zh-Hans',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Resident comprehensive income differs from business and investment categories.',
  },
  {
    id: 'CN-STA-002',
    market: 'CN',
    topic: 'tax',
    authority: 'STA Shanghai publication of national law',
    title: '中华人民共和国个人所得税法 — annual comprehensive-income rate table',
    url: 'https://shanghai.chinatax.gov.cn/zcfw/zcfgk/grsds/201809/t441789.html',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'zh-Hans',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'National law, not a Shanghai-only tax schedule.',
  },
  {
    id: 'CN-NPC-001',
    market: 'CN',
    topic: 'retirement',
    authority: 'National People’s Congress',
    title: '延迟退休改革决定通过！四部门相关负责人进行权威解读',
    url: 'https://www.npc.gov.cn/npc/c2/c30834/202409/t20240914_439634.html',
    effectiveDate: '2025-01-01',
    publicationDate: '2024-09-14',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'zh-Hans',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'CN-MOHRSS-001',
    market: 'CN',
    topic: 'retirement',
    authority: 'MOHRSS',
    title: '办法公布！2025年起弹性退休这样实施',
    url: 'https://www.mohrss.gov.cn/wap/xw/rsxw/202501/t20250101_533707.html',
    effectiveDate: '2025-01-01',
    publicationDate: '2025-01-01',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'zh-Hans',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'IND-NSO-001',
    market: 'IN',
    topic: 'inflation',
    authority: 'NSO / PIB',
    title: 'Consumer Price Index July 2026 — official annex tables',
    url: 'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2298615&lang=2&reg=48',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'MONTHLY',
    tier: 4,
    language: 'gu/en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
    notes: 'Gujarati release with English annex; July provisional national combined value. August release not verified.',
  },
  {
    id: 'IND-NSO-002',
    market: 'IN',
    topic: 'inflation',
    authority: 'MoSPI',
    title: 'Advance Release Calendar 2026–27, updated 25 May 2026',
    url: 'https://www.mospi.gov.in/uploads/documents/releaseCalender/1779709510470-ADVANCE%20RELEASE%20CALENDAR%202026-27%20Updated%2025.05.2026.pdf',
    effectiveDate: null,
    publicationDate: '2026-05-25',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'MONTHLY',
    tier: 4,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
  },
  {
    id: 'AUS-ABS-001',
    market: 'AU',
    topic: 'inflation',
    authority: 'ABS',
    title: 'Consumer Price Index, Australia, July 2026',
    url: 'https://www.abs.gov.au/statistics/economy/price-indexes-and-inflation/consumer-price-index-australia/jul-2026',
    effectiveDate: null,
    publicationDate: '2026-08-26',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'MONTHLY',
    tier: 4,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
  },
  {
    id: 'US-BLS-001',
    market: 'US',
    topic: 'inflation',
    authority: 'BLS',
    title: 'Consumer Price Index Summary — August 2026',
    url: 'https://www.bls.gov/news.release/cpi.nr0.htm',
    effectiveDate: null,
    publicationDate: '2026-09-11',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'MONTHLY',
    tier: 4,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
    notes: 'Mutable latest URL; preserve observation month and snapshot at ingestion.',
  },
  {
    id: 'UK-ONS-001',
    market: 'GB',
    topic: 'inflation',
    authority: 'ONS',
    title: 'Consumer price inflation, UK: July 2026',
    url: 'https://www.ons.gov.uk/economy/inflationandpriceindices/bulletins/consumerpriceinflation/july2026',
    effectiveDate: null,
    publicationDate: '2026-08-19',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'MONTHLY',
    tier: 4,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
  },
  {
    id: 'SG-MTI-001',
    market: 'SG',
    topic: 'inflation',
    authority: 'MAS / Ministry of Trade and Industry',
    title: 'Consumer Price Developments in July 2026',
    url: 'https://www.mti.gov.sg/newsroom/consumer-price-developments-in-july-2026/',
    effectiveDate: null,
    publicationDate: '2026-08-24',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'MONTHLY',
    tier: 3,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
  },
  {
    id: 'CN-NBS-001',
    market: 'CN',
    topic: 'inflation',
    authority: 'NBS',
    title: '2026年8月份居民消费价格同比上涨0.8%',
    url: 'https://www.stats.gov.cn/sj/zxfb/202609/t20260909_1965263.html',
    effectiveDate: null,
    publicationDate: '2026-09-09',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'MONTHLY',
    tier: 4,
    language: 'zh-Hans',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
    notes: 'New 2025-base series from January 2026.',
  },
  {
    id: 'UAE-CBUAE-003',
    market: 'AE',
    topic: 'inflation',
    authority: 'CBUAE, citing FCSC',
    title: 'Quarterly Economic Review, March 2026',
    url: 'https://www.centralbank.ae/media/lgnfakgc/qer-march_2026.pdf',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'QUARTERLY',
    tier: 3,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
    notes: 'Q4 2025 actual is historical; 2026 forecast is not an actual CPI observation.',
  },
  {
    id: 'IND-NSO-003',
    market: 'IN',
    topic: 'peer',
    authority: 'NSO',
    title: 'Household Consumption Expenditure Survey 2023–24, Report 592',
    url: 'https://mospi.gov.in/sites/default/files/publication_reports/Final_Report_HCES_2023-24L.pdf',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'RELEASE_EVENT',
    tier: 4,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
  },
  {
    id: 'IND-NSO-004',
    market: 'IN',
    topic: 'peer',
    authority: 'NSO',
    title: 'All India Debt & Investment Survey, NSS 77th round — Press Note',
    url: 'https://mospi.gov.in/sites/default/files/press_release/press_note-AIDIS--240821%20update.pdf',
    effectiveDate: null,
    publicationDate: '2021-09-10',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'RELEASE_EVENT',
    tier: 4,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
  },
  {
    id: 'AUS-ABS-002',
    market: 'AU',
    topic: 'peer',
    authority: 'ABS',
    title: 'Household Income and Wealth, Australia methodology, 2019–20',
    url: 'https://www.abs.gov.au/methodologies/household-income-and-wealth-australia-methodology/2019-20',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'RELEASE_EVENT',
    tier: 4,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
  },
  {
    id: 'AUS-ABS-003',
    market: 'AU',
    topic: 'peer',
    authority: 'ABS',
    title: 'Household Expenditure Survey, Australia: Summary of Results, 2015–16',
    url: 'https://www.abs.gov.au/statistics/economy/finance/household-expenditure-survey-australia-summary-results/latest-release',
    effectiveDate: null,
    publicationDate: '2017-09-13',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'RELEASE_EVENT',
    tier: 4,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
  },
  {
    id: 'US-FED-001',
    market: 'US',
    topic: 'peer',
    authority: 'Federal Reserve',
    title: 'Survey of Consumer Finances — 2022 release',
    url: 'https://www.federalreserve.gov/econres/scfindex.htm',
    effectiveDate: null,
    publicationDate: '2023-10-18',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'TRIENNIAL_RELEASE',
    tier: 3,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
  },
  {
    id: 'US-CENSUS-001',
    market: 'US',
    topic: 'peer',
    authority: 'US Census Bureau',
    title: '2025 CPS Household Income Table HINC-01: Selected Characteristics of Households by Total Money Income in 2024',
    url: 'https://www.census.gov/data/tables/2025/demo/cps/hinc-01.html',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL',
    tier: 4,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
    notes: 'Latest verified table, not certification that 2025 income release is unavailable.',
  },
  {
    id: 'US-BLS-002',
    market: 'US',
    topic: 'peer',
    authority: 'BLS',
    title: 'Consumer expenditures in 2024',
    url: 'https://www.bls.gov/opub/reports/consumer-expenditures/2024/home.htm',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL',
    tier: 4,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
  },
  {
    id: 'UK-ONS-002',
    market: 'GB',
    topic: 'peer',
    authority: 'ONS',
    title: 'Household total wealth in Great Britain: April 2020 to March 2022',
    url: 'https://www.ons.gov.uk/peoplepopulationandcommunity/personalandhouseholdfinances/incomeandwealth/bulletins/totalwealthingreatbritain/latest',
    effectiveDate: null,
    publicationDate: '2025-01-24',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'RELEASE_EVENT',
    tier: 4,
    language: 'en',
    scope: 'REGION_SPECIFIC',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
    notes: 'Accreditation suspended from Round 8; 13 June 2025 notice. Excludes Northern Ireland.',
  },
  {
    id: 'UK-ONS-003',
    market: 'GB',
    topic: 'peer',
    authority: 'ONS',
    title: 'Family spending in the UK: April 2024 to March 2025',
    url: 'https://www.ons.gov.uk/peoplepopulationandcommunity/personalandhouseholdfinances/expenditure/bulletins/familyspendingintheuk/latest',
    effectiveDate: null,
    publicationDate: '2026-06-11',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL',
    tier: 4,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
  },
  {
    id: 'UK-ONS-004',
    market: 'GB',
    topic: 'peer',
    authority: 'ONS',
    title: 'Average household income, UK: financial year ending 2025 — release notice',
    url: 'https://www.ons.gov.uk/releases/averagehouseholdincomeukfinancialyearending2025',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL',
    tier: 4,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
    notes: 'Not yet published as checked; provisional October 2026. Not a benchmark dataset.',
  },
  {
    id: 'SG-DOS-001',
    market: 'SG',
    topic: 'peer',
    authority: 'Singapore Department of Statistics',
    title: 'Key Household Income Trends, 2025',
    url: 'https://www.singstat.gov.sg/-/media/files/publications/households/pp-s32.ashx',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL',
    tier: 4,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
    notes: 'Market income / resident households definition differs from older employed-household work-income series.',
  },
  {
    id: 'SG-DOS-002',
    market: 'SG',
    topic: 'peer',
    authority: 'Singapore Department of Statistics',
    title: 'Key Indicators of the Household Expenditure Survey, 2012/13–2023',
    url: 'https://www.singstat.gov.sg/-/media/files/find_data/household/hes2023-key-indicators.ashx',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'FIVE_YEAR_RELEASE',
    tier: 4,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
  },
  {
    id: 'SG-DOS-003',
    market: 'SG',
    topic: 'peer',
    authority: 'Singapore Department of Statistics',
    title: 'Household Sector Balance Sheet, Fourth Quarter 2025',
    url: 'https://www.singstat.gov.sg/-/media/files/news/hh_bal4q2025.ashx',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'QUARTERLY',
    tier: 4,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
    notes: 'Aggregate sector accounting; no personal wealth percentile.',
  },
  {
    id: 'CN-NBS-002',
    market: 'CN',
    topic: 'peer',
    authority: 'NBS',
    title: '2025年居民收入和消费支出情况',
    url: 'https://www.stats.gov.cn/sj/zxfb/202601/t20260119_1962321.html',
    effectiveDate: null,
    publicationDate: '2026-01-19',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_QUARTERLY',
    tier: 4,
    language: 'zh-Hans',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
  },
  {
    id: 'CN-NBS-003',
    market: 'CN',
    topic: 'peer',
    authority: 'NBS',
    title: 'China Statistical Yearbook 2024 — Household survey introduction',
    url: 'https://www.stats.gov.cn/sj/ndsj/2024/html/sme06.htm',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL',
    tier: 4,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
  },
  {
    id: 'UAE-FCSC-001',
    market: 'AE',
    topic: 'peer',
    authority: 'FCSC / Ministry of Community Development',
    title: 'Community Development launches Household Income and Expenditure Survey 2024',
    url: 'https://fcsc.gov.ae/press-release/?e-page-176b1ad=48&e-page-1e9848e=7&e-page-5264904=2&e-page-6706913=8&e-page-e8b0ff1=14',
    effectiveDate: null,
    publicationDate: '2023-12-25',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'RELEASE_EVENT',
    tier: 4,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
    notes: 'Launch/sample target verified from official search extract; results and licence unavailable. Direct domain robots blocked.',
  },
  {
    id: 'US-SEC-001',
    market: 'US',
    topic: 'investment',
    authority: 'SEC Investor.gov',
    title: 'Beginners’ Guide to Asset Allocation, Diversification, and Rebalancing',
    url: 'https://www.investor.gov/additional-resources/general-resources/publications-research/info-sheets/beginners-guide-asset',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 2,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'LOW',
    notes: 'Principles only. Does not endorse FinatriX scoring or allocation percentages.',
  },
  {
    id: 'US-SEC-002',
    market: 'US',
    topic: 'cash',
    authority: 'SEC Investor.gov',
    title: 'Money Market Funds',
    url: 'https://www.investor.gov/introduction-investing/investing-basics/investment-products/mutual-funds-and-exchange-traded-5',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 2,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'LOW',
  },
  {
    id: 'US-CFPB-001',
    market: 'US',
    topic: 'heuristic',
    authority: 'CFPB',
    title: 'Analyzing budgets — teacher guide',
    url: 'https://files.consumerfinance.gov/f/documents/cfpb_building_block_activities_analyzing-budgets_guide.pdf',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2027-09-12',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 2,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'LOW',
  },
  {
    id: 'US-CFPB-002',
    market: 'US',
    topic: 'heuristic',
    authority: 'CFPB',
    title: 'What is a debt-to-income ratio?',
    url: 'https://www.consumerfinance.gov/ask-cfpb/what-is-a-debt-to-income-ratio-en-1791/',
    effectiveDate: null,
    publicationDate: '2023-08-28',
    lastVerified: '2026-09-12',
    reviewDue: '2027-09-12',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 2,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'LOW',
  },
  {
    id: 'AUS-ASIC-002',
    market: 'AU',
    topic: 'heuristic',
    authority: 'ASIC Moneysmart',
    title: 'Save for an emergency fund',
    url: 'https://moneysmart.gov.au/saving/save-for-an-emergency-fund',
    effectiveDate: null,
    publicationDate: '2026-09-09',
    lastVerified: '2026-09-12',
    reviewDue: '2027-09-12',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 2,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'LOW',
  },
  {
    id: 'AUS-ASIC-003',
    market: 'AU',
    topic: 'cash',
    authority: 'ASIC Moneysmart',
    title: 'Investments paying interest',
    url: 'https://moneysmart.gov.au/investments-paying-interest',
    effectiveDate: null,
    publicationDate: '2026-09-08',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 2,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'LOW',
  },
  {
    id: 'IND-RBI-001',
    market: 'IN',
    topic: 'cash',
    authority: 'RBI',
    title: 'Retail Direct Scheme — Frequently Asked Questions',
    url: 'https://www.rbi.org.in/scripts/faqview.aspx/faqview.aspx/scripts/FAQView.aspx?Id=145',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 3,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'LOW',
  },
  {
    id: 'US-TREASURY-001',
    market: 'US',
    topic: 'cash',
    authority: 'US Treasury',
    title: 'Treasury Bills',
    url: 'https://www.treasurydirect.gov/marketable-securities/treasury-bills/',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'LOW',
  },
  {
    id: 'UK-NSI-001',
    market: 'GB',
    topic: 'cash',
    authority: 'NS&I',
    title: 'Tax-free savings',
    url: 'https://www.nsandi.com/tax-free-saving',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'LOW',
    notes: 'Government backing context only. Promotional rates deliberately not extracted.',
  },
  {
    id: 'SG-MAS-001',
    market: 'SG',
    topic: 'cash',
    authority: 'MoneySense',
    title: 'Understanding bonds',
    url: 'https://www.moneysense.gov.sg/understanding-bonds/',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 2,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'LOW',
  },
  {
    id: 'UAE-MOF-001',
    market: 'AE',
    topic: 'cash',
    authority: 'Ministry of Finance',
    title: 'UAE’s First Sovereign Retail T-Sukuk Investment Opportunities for Citizens and Residents',
    url: 'https://mof.gov.ae/en/news/ministry-of-finance-unveils-uaes-first-sovereign-retail-t-sukuk-investment-opportunities-for-citizens-and-residents/',
    effectiveDate: null,
    publicationDate: '2026-06-17',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'LOW',
  },
  {
    id: 'CN-MOF-001',
    market: 'CN',
    topic: 'cash',
    authority: 'Ministry of Finance',
    title: '财政部、中国人民银行有关方面负责人就储蓄国债（电子式）相关事宜答记者问',
    url: 'https://www.mof.gov.cn/zhengwuxinxi/zhengcejiedu/2006/200805/t20080519_25636.htm',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'zh-Hans',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'LOW',
    notes: 'Instrument structure; current issue terms must be separately verified.',
  },
  {
    id: 'CN-MOF-002',
    market: 'CN',
    topic: 'cash',
    authority: 'Ministry of Finance',
    title: '中华人民共和国财政部公告2026年第1号',
    url: 'https://zwgls.mof.gov.cn/ywgg/202601/t20260108_3981581.htm',
    effectiveDate: null,
    publicationDate: '2026-01-08',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'zh-Hans',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'LOW',
  },
  {
    id: 'GLOBAL-FPA-001',
    market: 'US',
    topic: 'heuristic',
    authority: 'Journal of Financial Planning / William P. Bengen',
    title: 'Determining Withdrawal Rates Using Historical Data — 1994 article reprinted 2004',
    url: 'https://www.financialplanningassociation.org/sites/default/files/2021-04/MAR04%20Determining%20Withdrawal%20Rates%20Using%20Historical%20Data.pdf',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2027-09-12',
    cadence: 'METHODOLOGY_ONLY',
    tier: 6,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'LOW',
  },
  {
    id: 'GLOBAL-BOOK-001',
    market: 'US',
    topic: 'heuristic',
    authority: 'Simon & Schuster / Warren and Tyagi',
    title: 'All Your Worth',
    url: 'https://www.simonandschuster.com/books/All-Your-Worth/Elizabeth-Warren/A-Guide-to-Personal-Finances/9780743279741',
    effectiveDate: null,
    publicationDate: '2005-03-08',
    lastVerified: '2026-09-12',
    reviewDue: '2027-09-12',
    cadence: 'METHODOLOGY_ONLY',
    tier: 9,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'LOW',
    notes: 'Publisher confirms book provenance; not authority for financial outcomes.',
  },
  {
    id: 'IND-DICGC-002',
    market: 'IN',
    topic: 'deposit',
    authority: 'DICGC',
    title: 'Increase in Insurance Coverage for Depositors',
    url: 'https://oldwebsite.dicgc.org.in/pdf/2019/TheIncreaseInInsuranceCoverageForDepositorsFeb2020.pdf',
    effectiveDate: '2020-02-04',
    publicationDate: '2020-02-04',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'AUS-TREASURY-001',
    market: 'AU',
    topic: 'tax',
    authority: 'Australian Treasury',
    title: 'New cost of living tax cuts under Labor',
    url: 'https://ministers.treasury.gov.au/ministers/jim-chalmers-2022/media-releases/new-cost-living-tax-cuts-under-labor',
    effectiveDate: '2026-07-01',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Threshold corroboration; enacted Act is controlling source.',
  },
  {
    id: 'AUS-ATO-004',
    market: 'AU',
    topic: 'tax',
    authority: 'ATO',
    title: 'Medicare levy reduction or exemption — myTax 2025',
    url: 'https://www.ato.gov.au/api/public/content/0-fc9a4057-0427-4add-8fb3-ecc79dac458f',
    effectiveDate: null,
    publicationDate: '2025-06-02',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Historical 2% general reference; current low-income thresholds not verified.',
  },
  {
    id: 'IND-ITD-003',
    market: 'IN',
    topic: 'tax',
    authority: 'Income Tax Department',
    title: 'Income-tax Act 2025 — section 202',
    url: 'https://incometaxindia.gov.in/Documents/Act/Income-tax-Act-2025.pdf',
    effectiveDate: '2026-04-01',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Official indexed statute excerpt and Budget2026 FAQ corroboration. Direct full PDF timed out; not a consolidated full-law review.',
  },
  {
    id: 'IND-ITD-004',
    market: 'IN',
    topic: 'tax',
    authority: 'Income Tax Department',
    title: 'FAQs Budget 2026 — TY2026–27 rate table',
    url: 'https://incometaxindia.gov.in/Documents/Budget2026/FAQs-Budget-2026.pdf',
    effectiveDate: '2026-04-01',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'SG-CPF-006',
    market: 'SG',
    topic: 'retirement',
    authority: 'CPF Board',
    title: 'What is the Ordinary Wage ceiling?',
    url: 'https://www.cpf.gov.sg/service/article/what-is-the-ordinary-wage-ow-ceiling-mbr',
    effectiveDate: '2026-01-01',
    publicationDate: '2026-08-14',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'CN-MOHRSS-002',
    market: 'CN',
    topic: 'retirement',
    authority: 'MOHRSS',
    title: '个人养老金制度全面实施',
    url: 'https://chinajob.mohrss.gov.cn/h5/c/2024-12-20/421054.shtml',
    effectiveDate: null,
    publicationDate: '2024-12-20',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'zh-Hans',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'CN-MOHRSS-003',
    market: 'CN',
    topic: 'retirement',
    authority: 'MOHRSS',
    title: '个人养老金实施办法',
    url: 'https://www.mohrss.gov.cn/wap/zc/zcwj/202211/t20221104_489352.html',
    effectiveDate: null,
    publicationDate: '2022-11-04',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 5,
    language: 'zh-Hans',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'US-IRS-004',
    market: 'US',
    topic: 'tax',
    authority: 'IRS',
    title: 'Topic no. 403, Interest received',
    url: 'https://www.irs.gov/taxtopics/tc403',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'UK-HMRC-005',
    market: 'GB',
    topic: 'tax',
    authority: 'HMRC',
    title: 'Tax on savings interest',
    url: 'https://www.gov.uk/apply-tax-free-interest-on-savings',
    effectiveDate: null,
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
  },
  {
    id: 'CN-STA-003',
    market: 'CN',
    topic: 'tax',
    authority: 'STA / Ministry of Finance',
    title: '关于储蓄存款利息所得有关个人所得税政策的通知',
    url: 'https://www.chinatax.gov.cn/chinatax/n810341/n810765/n812171/200810/c1191167/content.html',
    effectiveDate: '2008-10-09',
    publicationDate: null,
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL_AND_EVENT',
    tier: 1,
    language: 'zh-Hans',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'HIGH',
    notes: 'Temporary exemption is category-specific, not a general exemption for investment gains.',
  },
  {
    id: 'IND-NSO-005',
    market: 'IN',
    topic: 'peer',
    authority: 'NSO',
    title: 'Periodic Labour Force Survey Annual Report 2025 — revised report',
    url: 'https://www.mospi.gov.in/uploads/publications_reports/publications_reports1780040415321_0624fb13-fb47-40bc-b470-7c7e9635c3ef_PLFS_2025_F_REV_29052026.pdf',
    effectiveDate: null,
    publicationDate: '2026-05-29',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL',
    tier: 4,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
    notes: 'Original release 27 March2026; revised report. Earnings concepts vary by employment type.',
  },
  {
    id: 'UK-ONS-005',
    market: 'GB',
    topic: 'peer',
    authority: 'ONS',
    title: 'Average household income, UK: Financial Year Ending 2024',
    url: 'https://www.ons.gov.uk/peoplepopulationandcommunity/personalandhouseholdfinances/incomeandwealth/bulletins/householddisposableincomeandinequality/latest',
    effectiveDate: null,
    publicationDate: '2025-05-02',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'ANNUAL',
    tier: 4,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
  },
  {
    id: 'US-CENSUS-002',
    market: 'US',
    topic: 'peer',
    authority: 'US Census Bureau',
    title: 'Tip Sheet Number 18 — September 4, 2026',
    url: 'https://www.census.gov/newsroom/tip-sheets/2026/tp26-18.html',
    effectiveDate: null,
    publicationDate: '2026-09-04',
    lastVerified: '2026-09-12',
    reviewDue: '2026-10-01',
    cadence: 'RELEASE_EVENT',
    tier: 4,
    language: 'en',
    scope: 'NATIONAL',
    verificationScope: 'Only the facts explicitly extracted in this pack; not a certification of all linked content.',
    changeImpact: 'MEDIUM',
    notes: '2025 income results scheduled 15 September2026, after pack cutoff.',
  },
  {
    "id": "AUS-ABS-004",
    "market": "AU",
    "topic": "peer",
    "authority": "ABS",
    "title": "Household Income and Wealth, Australia, 2019–20 — published tables",
    "url": "https://www.abs.gov.au/statistics/economy/finance/household-income-and-wealth-australia/2019-20",
    "effectiveDate": null,
    "publicationDate": "2022-05-25",
    "lastVerified": "2026-09-12",
    "reviewDue": "2027-02-01",
    "cadence": "RELEASE_EVENT",
    "tier": 4,
    "language": "en",
    "scope": "NATIONAL",
    "verificationScope": "Table 1a weekly gross household income median and Table 1b household net worth median; observation period 2019–20.",
    "changeImpact": "MEDIUM",
    "notes": "Historical summary only. Evidence and reuse terms archived in docs/evidence/seven-markets-2026-09-12. No percentile activation."
},
  {
    "id": "SG-DOS-005",
    "market": "SG",
    "topic": "peer",
    "authority": "Singapore Department of Statistics",
    "title": "Key Household Income Trends, 2025 — archived publication",
    "url": "https://www.singstat.gov.sg/files/b0eafa31-0ac6-4684-b2cd-4a264ce8d820.pdf",
    "effectiveDate": null,
    "publicationDate": null,
    "lastVerified": "2026-09-12",
    "reviewDue": "2027-02-01",
    "cadence": "RELEASE_EVENT",
    "tier": 4,
    "language": "en",
    "scope": "NATIONAL",
    "verificationScope": "Printed page 6 median monthly household market income; glossary pages 18–19. 2025 preliminary. Publication day not asserted.",
    "changeImpact": "MEDIUM",
    "notes": "Historical summary only. Evidence and reuse terms archived in docs/evidence/seven-markets-2026-09-12. No percentile activation."
},
  {
    "id": "CN-NBS-004",
    "market": "CN",
    "topic": "peer",
    "authority": "NBS",
    "title": "Households’ Income and Consumption Expenditure in 2025 — English release",
    "url": "https://www.stats.gov.cn/english/PressRelease/202601/t20260120_1962356.html",
    "effectiveDate": null,
    "publicationDate": "2026-01-20",
    "lastVerified": "2026-09-12",
    "reviewDue": "2027-02-01",
    "cadence": "RELEASE_EVENT",
    "tier": 4,
    "language": "en",
    "scope": "NATIONAL",
    "verificationScope": "Section I nationwide median annual per-capita disposable income. English release; original Chinese release dated 19 January.",
    "changeImpact": "MEDIUM",
    "notes": "Historical summary only. Evidence and reuse terms archived in docs/evidence/seven-markets-2026-09-12. No percentile activation."
},
];

/** Indexed once at module load; `sourceById` is called on every render path. */
const BY_ID: ReadonlyMap<string, ReferenceSource> = new Map(SOURCES.map((s) => [s.id, s]));

/** The record, or undefined. Never throws — a missing citation must not break a page. */
export function sourceById(id: string): ReferenceSource | undefined {
  return BY_ID.get(id);
}

/** Resolve a list of ids, silently dropping any that do not exist. */
export function sourcesByIds(ids: readonly string[]): readonly ReferenceSource[] {
  return ids.map(sourceById).filter((s): s is ReferenceSource => s !== undefined);
}
