import UIKit
import Capacitor

/**
 The scene lifecycle, as generated by Capacitor, with one change: the root view
 controller is FinatriX's `ViewController` rather than `CAPBridgeViewController`
 directly (see ViewController.swift).

 The three proxy calls below are what make deep links work, and they are load
 bearing rather than boilerplate:

  - `willConnectTo` carries the link that COLD-STARTED the app.
  - `openURLContexts` is the `co.finatrix.app://auth/callback` OAuth return.
  - `continue userActivity` is a verified Universal Link
    (`https://finatrix.co/...`) arriving while the app is already running.

 Each one reaches `src/native/bridge.ts` as an `appUrlOpen` event.
 */
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
    var window: UIWindow?

    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        guard let windowScene = scene as? UIWindowScene else { return }

        window = UIWindow(windowScene: windowScene)
        window?.rootViewController = ViewController()
        window?.makeKeyAndVisible()

        SceneDelegateProxy.shared.scene(scene, willConnectTo: session, options: connectionOptions)
    }

    func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
        SceneDelegateProxy.shared.scene(scene, openURLContexts: URLContexts)
    }

    func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
        SceneDelegateProxy.shared.scene(scene, continue: userActivity)
    }
}
